### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by perusio** [alibaba/nginx-http-sysguard#2]
1. What is meant by _system load_ is this the same load metric that you get from, e.g.,
   `uptime` in Linux?  In that case is an average and it requires some [thinking](https://en.wikipedia.org/wiki/Load_(computing\)) to set it to a given value.
2. What can the `action` parameter do? Is it merely an internal redirection to a location or can it redirect 
    to an external location or do more complex things?
3. The _swap ratio_ is relative to the maximum available? I think so but it should be made clear.
    Is it something like what you get from (Linux):
   
   ```
    cat /proc/meminfo | awk '/^SwapTotal:/ {spt=$2} /^SwapFree:/ {spf=$2}
    END {printf("| swp %d%%",(1-spf/spt)*100)}'
   ```

**Comment by perusio** [comment]
Ah yes. I'm wondering if the patch will work in the 1.3.x branch.

**Comment by zhuzhaoyuan** [comment]
Hi António!

Simple answers to your questions:
1. Yes, it is equal to the value of 'uptime' command. We choose the load average of the last one minute.
2. The 'action' parameter is just an internal redirection when the threshold is reached.
3. It's the swap_used/swap_total ratio.

This patch should work in the 1.3.x branch.

**Comment by zhuzhaoyuan** [comment]
@lifeibo 

Could you please provide a new patch against nginx-1.3.x branch? The name of 'nginx_sysguard_1.2.5.patch' is a little bit confusing just as António mentioned. Thanks.

**Comment by lifeibo** [comment]
Hi perusio,

I have made a patch 'nginx_sysguard_1.3.9.patch' for nginx 1.3.9, you can try it again.

Thanks.
